declare global {
	namespace Acore {
		class Player extends Unit {
			static byGuid(guid: ObjectGuid): Player | undefined;
			static byName(name: string): Player | undefined;
			static allInWorld(): Player[];

			readonly race: Races;
			readonly raceMask: number;
			readonly clazz: Classes;
			readonly classMask: number;
			readonly teamId: TeamId;
			readonly guildId: number;
			readonly isInGroup: boolean;
			readonly isInGuild: boolean;
			readonly isRested: boolean;
			readonly hasCorpse: boolean;
			readonly isMaxLevel: boolean;
			readonly activeSpec: number;
			readonly specsCount: number;
			readonly restBonus: number;
			readonly xp: number;
			readonly battlegroundTypeId: BattlegroundTypeId;
			readonly gmRank: AccountTypes;
			readonly accountId: number;
			readonly accountFlags: AccountFlag;
			readonly accountName: string;
			readonly completedQuestsCount: number;
			readonly corpse: Corpse | undefined;
			readonly playerIP: string;
			readonly mailCount: number;
			readonly mostPointsTalentTree: number;
			readonly group: Group | undefined;
			readonly difficulty: Difficulty;
			readonly inventoryFreeSlots: number;
			readonly canSpeak: boolean;
			readonly canUninviteFromGroup: boolean;
			readonly inBattlegroundQueue: boolean;
			readonly inArena: boolean;
			readonly inBattleground: boolean;
			readonly hasTankSpec: boolean;
			readonly hasMeleeSpec: boolean;
			readonly hasCasterSpec: boolean;
			readonly hasHealSpec: boolean;
			readonly hasPet: boolean;
			readonly canTameExoticPets: boolean;
			readonly canPetResurrect: boolean;
			readonly canResummonPet: boolean;
			readonly inRandomLfgDungeon: boolean;
			readonly isUsingLfg: boolean;
			readonly achievementPoints: number;
			readonly dodgeFromAgility: number;
			readonly meleeCritFromAgility: number;
			readonly spellCritFromIntellect: number;
			readonly ammoDPS: number;
			readonly canSeeDKPet: boolean;
			readonly isImmuneToDamage: boolean;
			readonly battlegroundId: number;
			readonly championingFactionId: number;
			readonly chatTag: PlayerChatTag;
			readonly dbLocaleIndex: LocaleConstant;
			readonly dbcLocale: LocaleConstant;
			readonly latency: Temporal.Duration;
			readonly groupInvite: Group | undefined;
			/**
			 * Keeping this for parity with C++, but it has a weak name and an awkward type.
			 *
			 * Some may prefer the mod-nodejs invention {@link loginTimestamp} instead.
			 */
			readonly inGameTime: number;
			readonly loginTimestamp: Temporal.Instant;
			readonly healthBonusFromStamina: number;
			readonly manaBonusFromIntellect: number;
			readonly originalGroup: number
			readonly originalSubGroup: number;
			// used for proper set phase for DB at GM-mode creature/GO spawn
			readonly phaseMaskForSpawn: number;
			readonly selectedPlayer: Player | undefined;
			readonly selectedUnit: Unit | undefined;
			readonly shield: Item | undefined;
			readonly shieldBlockValue: number;
			readonly subGroup: number;
			readonly todayHonorPoints: number;
			readonly todayKills: number;
			readonly trader: Player | undefined;
			readonly yesterdayHonorPoints: number;
			readonly yesterdayKills: number;
			readonly recruiterId: number;
			readonly bankFreeSlots: number;
			readonly levelPlayedTime: Temporal.Duration;
			readonly averageItemLevel: number;
			readonly totalPlayedTime: Temporal.Duration;
			readonly guildName: string;
			readonly runesState: number;
			// false if mod_playerbots is not installed
			readonly isBot: boolean;
			readonly isHorde: boolean;
			readonly isAlliance: boolean;
			readonly isInArena: boolean;
			readonly isInBattleground: boolean;
			readonly isInBattlegroundQueue: boolean;
			readonly canTitanGrip: boolean;
			readonly pet: Pet | undefined;
			readonly homebind: Homebind;
			readonly talentTreePoints: number[];
			readonly completedAchievementsCount: number;
			readonly completedAchievementsCountExcludingFeatsOfStrength: number;
			readonly currentQuestIds: number[];
			readonly spells: number[];
			readonly knownTaxiNodes: number[];
			readonly isFFAPvP: boolean;
			readonly isInArenaTeam: boolean;

			money: number;
			drunkValue: number;
			freeTalentPoints: number;
			arenaPoints: number;
			honorPoints: number;
			lifetimeKills: number;
			taxiCheat: boolean;
			gmChat: boolean;
			isPvP: boolean;
			bonusTalentCount: number;
			canTeleport: boolean;
			lastPetNumber: number;
			lastPetSpell: number;
			temporaryUnsummonedPetNumber: number;
			acceptWhispers: boolean;
			gmVisible: boolean;
			creationTime: Temporal.Instant;
			guildRank: number;
			isGM: boolean;
			afk: boolean;
			dnd: boolean;
			isSpectator: boolean;
			canBlock: boolean;
			canParry: boolean;
			viewpoint: WorldObject | undefined;
			gossipMenuId: number;

			hasAccountFlag(flag: AccountFlag): boolean;
			setAccountFlag(flag: AccountFlag): boolean;
			clearAccountFlag(flag: AccountFlag): boolean;
			resetTalentsCost(): void;
			getRaceAsString(locale?: LocaleConstant): string;
			getClassAsString(locale?: LocaleConstant): string;
			hasSpell(spellId: number): boolean;
			hasQuest(questId: number): boolean;
			hasItemCount(itemId: number, count?: number, checkBank?: false): boolean;
			getItemCount(itemId: number, checkBank?: false, skipItem?: Item): number;
			getReputationWith(factionId: number): number;
			getReputationRankWith(factionId: number): ReputationRank;
			getQuestStatus(questId: number): QuestStatus;
			// TODO: verify correctness
			getEquippedItemBySlot(slot: number): Item | undefined;
			// TODO: verify correctness
			getInventoryItem(slot: number): Item | undefined;
			// TODO: verify correctness
			getBankItem(slot: number): Item | undefined;
			getBarberShopCost(hairstyle: number, haircolor: number, facialhair: number, skincolor?: number): number;
			getSkillValue(skill: SkillType): number;
			getMaxSkillValue(skill: SkillType): number;
			hasTalent(talentId: number, spec?: number): boolean;
			hasAchieved(achievementId: number): boolean;
			hasQuestForItem(itemId: number, excludeQuestId?: number, turnIn?: boolean, showInLoot?: Box<boolean>): boolean;
			canUseItem(itemId: number): boolean;
			hasSpellCooldown(spellId: number): boolean;
			canShareQuest(questId: number): boolean;
			isGroupVisibleFor(player: Player): boolean;
			isInSameRaidWith(player: Player): boolean;
			isInSameGroupWith(player: Player): boolean;
			isHonorOrXPTarget(target: Unit): boolean;
			isVisibleFor(player: Player): boolean;
			hasKnownTaxiNode(nodeId: number): boolean;
			isAtGroupRewardDistanceFor(target: Unit): boolean;
			isAtLootRewardDistanceFor(target: Unit): boolean;
			canEquipNewItem(itemId: number, slot: number, swap: boolean): boolean;
			isDailyQuestDone(quest: Quest): boolean;
			canSeeStartQuest(quest: Quest): boolean;
			canInteractWithQuestGiver(target: WorldObject): boolean;
			hasArmorProficiency(armor: ItemSubclassArmor): boolean;
			hasWeaponProficiency(weapon: ItemSubclassWeapon): boolean;
			getGlyph(slot: number): GlyphPropertiesEntry | undefined;
			getBaseSkillValue(skill: SkillType): number;
			getPureSkillValue(skill: SkillType): number;
			getPureMaxSkillValue(skill: SkillType): number;
			getSkillPermBonusValue(skill: SkillType): number;
			getSkillTempBonusValue(skill: SkillType): number;
			hasQuestFor(gameObject: GameObject): boolean;
			getQuestLevel(quest: Quest): number;
			getQuestSlotQuestId(slot: number): number;
			hasTitle(titleId: number): boolean;
			hasTitleByIndex(bitIndex: number): boolean;
			hasItem(entryId: number, count?: number): boolean;
			getItemByEntry(entryId: number): Item | undefined;
			// TODO: consistent naming
			getItemByGUID(guid: ObjectGuid): Item | undefined;
			getItemByPos(bag: number, slot: number): Item | undefined;
			calculateReputationGain(source: ReputationSource, creatureOrQuestLevel: number, rep: number, factionId: number, noQuestBonus?: boolean): number;
			getNearbyGameObject(entryId: number, range: number): GameObject | undefined;
			getNextRandomRaidMember(radius: number): Player | undefined;
			getReqKillOrCastCurrentCount(questId: number, entry: number): number;
			getQuestRewardStatus(questId: number): boolean;
			getSpellCooldownDelay(spellId: number): number;
			hasAtLoginFlag(flag: AtLoginFlags): boolean;
			hasSkill(skill: SkillType): boolean;
			getAchievementCriteriaProgress(criteriaId: number): number;


			sendSystemMessage(msg: string): void;
			learnSpell(spellId: number, temporary?: boolean, learnFromSkill?: boolean): void;
			removeSpell(spellId: number, temporary?: boolean, learnFromSkill?: boolean): void;
			modifyMoney(amount: number): boolean;
			teleport(mapId: number, x: number, y: number, z: number, o: number, options?: TeleportToOptions, target?: Unit, newInstance?: boolean): boolean;
			resurrect(restorePct?: number, applySickness?: boolean): void;
			equipItem(itemId: number, slot: number): Item | undefined;
			mute(duration: Temporal.Duration): void;
			giveXP(amount: number, target: Unit, groupRate?: number, isLfgReward?: boolean): void;
			toggleDND(): void;
			toggleAFK(): void;
			resetTalents(noResetCost?: boolean): void;
			talkedToCreature(entry: number, guid: ObjectGuid): void;
			killedMonsterCredit(entry: number, guid?: ObjectGuid): void;
			addQuest(quest: Quest, questGiver?: Object): void;
			removeQuest(questId: number): void;
			completeQuest(questId: number): void;
			failQuest(questId: number): void;
			incompleteQuest(questId: number): void;
			abandonQuest(questId: number): void;
			addItem(itemId: number, count?: number): boolean;
			removeItem(itemId: number, count?: number): void;
			resetSpellCooldown(spellId: number, target: Unit): void;
			resetAllCooldowns(): void;
			sendNotification(msg: string): void;
			sendAreaTriggerMessage(msg: string): void;
			sendAddonMessage(prefix: string, msg: string): void;
			durabilityRepairAll(cost: boolean, discountMod: number, guildBank: boolean): number;
			durabilityRepair(slot: number, cost: boolean, discountMod: number, guildBank: boolean): number;
			durabilityLossAll(percent: number, inventory: boolean): void;
			durabilityPointsLossAll(points: number, inventory: boolean): void;
			advanceSkillsToMax(): void;
			advanceAllSkills(step: number): void;
			advanceSkill(skill: SkillType, step: number): boolean;
			summonPet(entry: number, x: number, y: number, z: number, o: number, petType?: PetType, duration?: Temporal.Duration, healthPct?: number): Pet | undefined;
			createPet(entry: number, spellId?: number): Pet | undefined;
			returnPet(entry: number, mode?: PetSaveMode, returnReagent?: boolean): void;
			unsummonPetTemporarilyIfAny(): void;
			resummonPetIfTemporarilyUnsummoned(): void;
			inviteToGroup(target: Player): boolean;
			createGroupWith(target: Player): Group | undefined;
			removeFromGroup(method?: RemoveMethod): void;
			addLifetimeKills(kills: number): void;
			removeLifetimeKills(kills: number): void;
			sendTaxiMenu(creature: Creature): void;
			sendSpiritResurrect(): void;
			sendShowBank(banker: ObjectGuid): void;
			sendAuctionMenu(auctioneer: Creature): void;
			unbindInstance(instanceId: number, difficulty?: Difficulty): void;
			unbindAllInstances(): void;
			leaveBattleground(): void;
			logoutPlayer(save?: boolean): void;
			saveToDB(): void;
			modifyArenaPoints(pts: number): void;
			modifyHonorPoints(pts: number): void;
			setGender(gender: Gender): void;
			setPlayerLock(apply?: boolean): void;
			setAtLoginFlag(flags: AtLoginFlags): void;
			doRandomRoll(min: number, max: number): number;
			sendCinematicStart(cinematicId: number): void;
			sendMovieStart(movieId: number): void;
			sendTrainerList(trainer: Creature): void;
			sendListInventory(vendor: WorldObject, overrideEntry?: number): void;
			sendGuildInvite(playerName: string): void;
			sendShowMailBox(mailbox: GameObject): void;
			areaExploredOrEventHappens(eventId: number): void;
			groupEventHappens(questId: number, eventObject?: WorldObject): void;
			takeEnvironmentalDamage(type: EnviromentalDamage, amount: number): number;
			canCompleteRepeatableQuest(quest: Quest): boolean;
			canRewardQuest(quest: Quest, msg: boolean): boolean;
			canCompleteQuest(questId: number): boolean;
			canTakeQuest(quest: Quest, msg: boolean): boolean;
			canAddQuest(quest: Quest, msg: boolean): boolean;
			addArmorProficiency(proficiency: ItemSubclassMaskArmor): void;
			addBonusTalent(count: number): void;
			learnTalent(id: number, rank?: number): void;
			addWeaponProficiency(proficiency: ItemSubclassMaskWeapon): void;
			learnPetTalent(talentId: number, talentRank: number): void;
			resetPetTalents(): void;
			setGlyph(glyphId: number, slot: number): void;
			completedAchievement(achievement: AchievementEntry): void;
			resetAchievements(): void;
			bindToInstance(): void;
			kickPlayer(): void;
			runCommand(command: string): void;
			removeFromBattlegroundRaid(): void;
			gossipAddQuests(source: Creature | GameObject): void;
			gossipClearMenu(): void;
			gossipComplete(): void;
			gossipMenuAddItem(menuItemId: number, icon: GossipOptionIcon, message: string, sender: number, action: GossipAction, boxMessage: string, boxMoney: number, coded?: boolean): void;
			gossipSendMenuToCreature(titleTextId: number, creature: ObjectGuid): void;
			gossipSendPOI(poiId: number): void;
			setSkill(type: SkillType, value: number): void;
			applyRatingMod(rating: CombatRating, value: number): void;
			setQuestStatus(questId: number, status: QuestStatus): void;
			removeRewardedQuest(questId: number): void;
			rewardQuest(quest: Quest, reward?: number, questGiver?: Creature | GameObject, announce?: boolean, isLfgReward?: boolean): void;
			removeActiveQuest(questId: number): void;
			// get the bit index from Acore.getCharTitlesEntry(id).bitIndex
			setKnownTitle(titleBitIndex: number): void;
			// get the bit index from Acore.getCharTitlesEntry(id).bitIndex
			unsetKnownTitle(titleBitIndex: number): void;
			initTaxiNodesForLevel(): void;
			startTaxiByTaxiPathId(taxiPathId: number, spellId?: number): boolean;
			startTaxiByNodes(nodeIds: readonly number[], npc?: Creature, spellId?: number): boolean;
			toggleInstantFlight(): void;
			removeAmmo(): void;
			setAmmo(entry: number): void;
			spawnBones(): void;
			gainSpellComboPoints(amount: number): void;
			applySpellPowerBonus(amount: number, apply?: boolean): void;
			resetTypeCooldowns(type: number): void;
			removeArenaSpellCooldowns(): void;
			setShowDKPet(show: boolean): void;
			setPvPDeath(isPvPDeath: boolean): void;
			setPlayerFlag(flag: PlayerFlags): void;
			removePlayerFlag(flag: PlayerFlags): void;
			getPlayerSettingValue(source: string, index: number): number;
			// this actually consumes it from the rest bonus pool
			getXPRestBonus(xp: number): number;
			setBindPoint(x: number, y: number, z: number, mapId: number, areaId: number): number;
			setFactionForRace(race: Races): void;
			setKnownTaxiNodes(nodes: readonly number[]): void;
			// setReputation(faction: FactionEntry, value: number): void;
			setRestState(triggerId: number): void;
			updatePlayerSetting(source: string, index: number, value: number): void;
			durabilityPointLossForEquipSlot(slot: EquipmentSlots): void;
			durabilityPointsLoss(item: Item, points: number): void;
			sendQuestTemplate(questGiver: ObjectGuid, quest: Quest, activateAccept?: boolean): void;
			sendTabardVendorActivate(creature: ObjectGuid): void;
			sendUpdateWorldState(dataId: number, value: number): void;
			removedInsignia(looter: Player): void;
			killPlayer(): void;
			textEmote(text: string): void;
			removeBonusTalent(count: number): void;
			storeNewItemInBestSlots(itemId: number, itemCount: number): boolean;
		}
	}
}
export {};
