declare global {
	const enum CombatRating {
		CR_WEAPON_SKILL             = 0,
		CR_DEFENSE_SKILL            = 1,
		CR_DODGE                    = 2,
		CR_PARRY                    = 3,
		CR_BLOCK                    = 4,
		CR_HIT_MELEE                = 5,
		CR_HIT_RANGED               = 6,
		CR_HIT_SPELL                = 7,
		CR_CRIT_MELEE               = 8,
		CR_CRIT_RANGED              = 9,
		CR_CRIT_SPELL               = 10,
		CR_HIT_TAKEN_MELEE          = 11,
		CR_HIT_TAKEN_RANGED         = 12,
		CR_HIT_TAKEN_SPELL          = 13,
		CR_CRIT_TAKEN_MELEE         = 14,
		CR_CRIT_TAKEN_RANGED        = 15,
		CR_CRIT_TAKEN_SPELL         = 16,
		CR_HASTE_MELEE              = 17,
		CR_HASTE_RANGED             = 18,
		CR_HASTE_SPELL              = 19,
		CR_WEAPON_SKILL_MAINHAND    = 20,
		CR_WEAPON_SKILL_OFFHAND     = 21,
		CR_WEAPON_SKILL_RANGED      = 22,
		CR_EXPERTISE                = 23,
		CR_ARMOR_PENETRATION        = 24,
	}
}
export {};
