declare global {
	const enum GuildEventLogTypes {
		GUILD_EVENT_LOG_INVITE_PLAYER = 1,
		GUILD_EVENT_LOG_JOIN_GUILD = 2,
		GUILD_EVENT_LOG_PROMOTE_PLAYER = 3,
		GUILD_EVENT_LOG_DEMOTE_PLAYER = 4,
		GUILD_EVENT_LOG_UNINVITE_PLAYER = 5,
		GUILD_EVENT_LOG_LEAVE_GUILD = 6
	}
}
export {};
