declare global {
	const enum GuildBankEventLogTypes {
		GUILD_BANK_LOG_DEPOSIT_ITEM = 1,
		GUILD_BANK_LOG_WITHDRAW_ITEM = 2,
		GUILD_BANK_LOG_MOVE_ITEM = 3,
		GUILD_BANK_LOG_DEPOSIT_MONEY = 4,
		GUILD_BANK_LOG_WITHDRAW_MONEY = 5,
		GUILD_BANK_LOG_REPAIR_MONEY = 6,
		GUILD_BANK_LOG_MOVE_ITEM2 = 7,
		GUILD_BANK_LOG_UNK1 = 8,
		GUILD_BANK_LOG_BUY_SLOT = 9
	}
}
export {};
