declare global {
	// values based at Holidays.dbc
	const enum HolidayIds {
		HOLIDAY_NONE                     = 0,

		HOLIDAY_FIREWORKS_SPECTACULAR    = 62,
		HOLIDAY_FEAST_OF_WINTER_VEIL     = 141,
		HOLIDAY_NOBLEGARDEN              = 181,
		HOLIDAY_CHILDRENS_WEEK           = 201,
		HOLIDAY_CALL_TO_ARMS_AV          = 283,
		HOLIDAY_CALL_TO_ARMS_WS          = 284,
		HOLIDAY_CALL_TO_ARMS_AB          = 285,
		HOLIDAY_FISHING_EXTRAVAGANZA     = 301,
		HOLIDAY_HARVEST_FESTIVAL         = 321,
		HOLIDAY_HALLOWS_END              = 324,
		HOLIDAY_LUNAR_FESTIVAL           = 327,
		// HOLIDAY_LOVE_IS_IN_THE_AIR    = 335, unused/duplicated
		HOLIDAY_FIRE_FESTIVAL            = 341,
		HOLIDAY_CALL_TO_ARMS_EY          = 353,
		HOLIDAY_BREWFEST                 = 372,
		HOLIDAY_DARKMOON_FAIRE_ELWYNN    = 374,
		HOLIDAY_DARKMOON_FAIRE_THUNDER   = 375,
		HOLIDAY_DARKMOON_FAIRE_SHATTRATH = 376,
		HOLIDAY_PIRATES_DAY              = 398,
		HOLIDAY_CALL_TO_ARMS_SA          = 400,
		HOLIDAY_PILGRIMS_BOUNTY          = 404,
		HOLIDAY_WOTLK_LAUNCH             = 406,
		HOLIDAY_DAY_OF_DEAD              = 409,
		HOLIDAY_CALL_TO_ARMS_IC          = 420,
		HOLIDAY_LOVE_IS_IN_THE_AIR       = 423,
		HOLIDAY_KALU_AK_FISHING_DERBY    = 424,
	}
}
export {};
