declare global {
	const enum ItemSubclassContainer {
		ITEM_SUBCLASS_CONTAINER                     = 0,
		ITEM_SUBCLASS_SOUL_CONTAINER                = 1,
		ITEM_SUBCLASS_HERB_CONTAINER                = 2,
		ITEM_SUBCLASS_ENCHANTING_CONTAINER          = 3,
		ITEM_SUBCLASS_ENGINEERING_CONTAINER         = 4,
		ITEM_SUBCLASS_GEM_CONTAINER                 = 5,
		ITEM_SUBCLASS_MINING_CONTAINER              = 6,
		ITEM_SUBCLASS_LEATHERWORKING_CONTAINER      = 7,
		ITEM_SUBCLASS_INSCRIPTION_CONTAINER         = 8,
	}
	// mod-nodejs invention
	const enum ItemSubclassMaskContainer {
		ITEM_SUBCLASS_MASK_CONTAINER                = 1 << ItemSubclassContainer.ITEM_SUBCLASS_CONTAINER,
		ITEM_SUBCLASS_MASK_SOUL_CONTAINER           = 1 << ItemSubclassContainer.ITEM_SUBCLASS_SOUL_CONTAINER,
		ITEM_SUBCLASS_MASK_HERB_CONTAINER           = 1 << ItemSubclassContainer.ITEM_SUBCLASS_HERB_CONTAINER,
		ITEM_SUBCLASS_MASK_ENCHANTING_CONTAINER     = 1 << ItemSubclassContainer.ITEM_SUBCLASS_ENCHANTING_CONTAINER,
		ITEM_SUBCLASS_MASK_ENGINEERING_CONTAINER    = 1 << ItemSubclassContainer.ITEM_SUBCLASS_ENGINEERING_CONTAINER,
		ITEM_SUBCLASS_MASK_GEM_CONTAINER            = 1 << ItemSubclassContainer.ITEM_SUBCLASS_GEM_CONTAINER,
		ITEM_SUBCLASS_MASK_MINING_CONTAINER         = 1 << ItemSubclassContainer.ITEM_SUBCLASS_MINING_CONTAINER,
		ITEM_SUBCLASS_MASK_LEATHERWORKING_CONTAINER = 1 << ItemSubclassContainer.ITEM_SUBCLASS_LEATHERWORKING_CONTAINER,
		ITEM_SUBCLASS_MASK_INSCRIPTION_CONTAINER    = 1 << ItemSubclassContainer.ITEM_SUBCLASS_INSCRIPTION_CONTAINER,
	}
}
export {};
