declare global {
	const enum ItemSubclassWeapon {
		ITEM_SUBCLASS_WEAPON_AXE                    = 0,
		ITEM_SUBCLASS_WEAPON_AXE2                   = 1,
		ITEM_SUBCLASS_WEAPON_BOW                    = 2,
		ITEM_SUBCLASS_WEAPON_GUN                    = 3,
		ITEM_SUBCLASS_WEAPON_MACE                   = 4,
		ITEM_SUBCLASS_WEAPON_MACE2                  = 5,
		ITEM_SUBCLASS_WEAPON_POLEARM                = 6,
		ITEM_SUBCLASS_WEAPON_SWORD                  = 7,
		ITEM_SUBCLASS_WEAPON_SWORD2                 = 8,
		ITEM_SUBCLASS_WEAPON_obsolete               = 9,
		ITEM_SUBCLASS_WEAPON_STAFF                  = 10,
		ITEM_SUBCLASS_WEAPON_EXOTIC                 = 11,
		ITEM_SUBCLASS_WEAPON_EXOTIC2                = 12,
		ITEM_SUBCLASS_WEAPON_FIST                   = 13,
		ITEM_SUBCLASS_WEAPON_MISC                   = 14,
		ITEM_SUBCLASS_WEAPON_DAGGER                 = 15,
		ITEM_SUBCLASS_WEAPON_THROWN                 = 16,
		ITEM_SUBCLASS_WEAPON_SPEAR                  = 17,
		ITEM_SUBCLASS_WEAPON_CROSSBOW               = 18,
		ITEM_SUBCLASS_WEAPON_WAND                   = 19,
		ITEM_SUBCLASS_WEAPON_FISHING_POLE           = 20,
	}
	// mod-nodejs invention
	const enum ItemSubclassMaskWeapon {
		ITEM_SUBCLASS_MASK_WEAPON_AXE               = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_AXE,
		ITEM_SUBCLASS_MASK_WEAPON_AXE2              = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_AXE2,
		ITEM_SUBCLASS_MASK_WEAPON_BOW               = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_BOW,
		ITEM_SUBCLASS_MASK_WEAPON_GUN               = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_GUN,
		ITEM_SUBCLASS_MASK_WEAPON_MACE              = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_MACE,
		ITEM_SUBCLASS_MASK_WEAPON_MACE2             = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_MACE2,
		ITEM_SUBCLASS_MASK_WEAPON_POLEARM           = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_POLEARM,
		ITEM_SUBCLASS_MASK_WEAPON_SWORD             = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_SWORD,
		ITEM_SUBCLASS_MASK_WEAPON_SWORD2            = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_SWORD2,
		ITEM_SUBCLASS_MASK_WEAPON_obsolete          = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_obsolete,
		ITEM_SUBCLASS_MASK_WEAPON_STAFF             = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_STAFF,
		ITEM_SUBCLASS_MASK_WEAPON_EXOTIC            = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_EXOTIC,
		ITEM_SUBCLASS_MASK_WEAPON_EXOTIC2           = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_EXOTIC2,
		ITEM_SUBCLASS_MASK_WEAPON_FIST              = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_FIST,
		ITEM_SUBCLASS_MASK_WEAPON_MISC              = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_MISC,
		ITEM_SUBCLASS_MASK_WEAPON_DAGGER            = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_DAGGER,
		ITEM_SUBCLASS_MASK_WEAPON_THROWN            = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_THROWN,
		ITEM_SUBCLASS_MASK_WEAPON_SPEAR             = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_SPEAR,
		ITEM_SUBCLASS_MASK_WEAPON_CROSSBOW          = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_CROSSBOW,
		ITEM_SUBCLASS_MASK_WEAPON_WAND              = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_WAND,
		ITEM_SUBCLASS_MASK_WEAPON_FISHING_POLE      = 1 << ItemSubclassWeapon.ITEM_SUBCLASS_WEAPON_FISHING_POLE,
	}
}
export {};
