declare global {
	const enum ItemSubclassRecipe {
		ITEM_SUBCLASS_BOOK                          = 0,
		ITEM_SUBCLASS_LEATHERWORKING_PATTERN        = 1,
		ITEM_SUBCLASS_TAILORING_PATTERN             = 2,
		ITEM_SUBCLASS_ENGINEERING_SCHEMATIC         = 3,
		ITEM_SUBCLASS_BLACKSMITHING                 = 4,
		ITEM_SUBCLASS_COOKING_RECIPE                = 5,
		ITEM_SUBCLASS_ALCHEMY_RECIPE                = 6,
		ITEM_SUBCLASS_FIRST_AID_MANUAL              = 7,
		ITEM_SUBCLASS_ENCHANTING_FORMULA            = 8,
		ITEM_SUBCLASS_FISHING_MANUAL                = 9,
		ITEM_SUBCLASS_JEWELCRAFTING_RECIPE          = 10,
	}
	// mod-nodejs invention
	const enum ItemSubclassMaskRecipe {
		ITEM_SUBCLASS_MASK_BOOK                     = 1 << ItemSubclassRecipe.ITEM_SUBCLASS_BOOK,
		ITEM_SUBCLASS_MASK_LEATHERWORKING_PATTERN   = 1 << ItemSubclassRecipe.ITEM_SUBCLASS_LEATHERWORKING_PATTERN,
		ITEM_SUBCLASS_MASK_TAILORING_PATTERN        = 1 << ItemSubclassRecipe.ITEM_SUBCLASS_TAILORING_PATTERN,
		ITEM_SUBCLASS_MASK_ENGINEERING_SCHEMATIC    = 1 << ItemSubclassRecipe.ITEM_SUBCLASS_ENGINEERING_SCHEMATIC,
		ITEM_SUBCLASS_MASK_BLACKSMITHING            = 1 << ItemSubclassRecipe.ITEM_SUBCLASS_BLACKSMITHING,
		ITEM_SUBCLASS_MASK_COOKING_RECIPE           = 1 << ItemSubclassRecipe.ITEM_SUBCLASS_COOKING_RECIPE,
		ITEM_SUBCLASS_MASK_ALCHEMY_RECIPE           = 1 << ItemSubclassRecipe.ITEM_SUBCLASS_ALCHEMY_RECIPE,
		ITEM_SUBCLASS_MASK_FIRST_AID_MANUAL         = 1 << ItemSubclassRecipe.ITEM_SUBCLASS_FIRST_AID_MANUAL,
		ITEM_SUBCLASS_MASK_ENCHANTING_FORMULA       = 1 << ItemSubclassRecipe.ITEM_SUBCLASS_ENCHANTING_FORMULA,
		ITEM_SUBCLASS_MASK_FISHING_MANUAL           = 1 << ItemSubclassRecipe.ITEM_SUBCLASS_FISHING_MANUAL,
		ITEM_SUBCLASS_MASK_JEWELCRAFTING_RECIPE     = 1 << ItemSubclassRecipe.ITEM_SUBCLASS_JEWELCRAFTING_RECIPE,
	}
}
export {};
