declare global {
	const enum ReputationSource {
		REPUTATION_SOURCE_KILL,
		REPUTATION_SOURCE_QUEST,
		REPUTATION_SOURCE_DAILY_QUEST,
		REPUTATION_SOURCE_WEEKLY_QUEST,
		REPUTATION_SOURCE_MONTHLY_QUEST,
		REPUTATION_SOURCE_REPEATABLE_QUEST,
		REPUTATION_SOURCE_SPELL,
	}
}
export {};
