declare global {
	// ***********************************
	// Spell Attributes definitions
	// ***********************************

	const enum SpellAttr0 {
		SPELL_ATTR0_PROC_FAILURE_BURNS_CHARGE        = 0x00000001, // TITLE Proc Failure Burns Charge
		SPELL_ATTR0_USES_RANGED_SLOT                 = 0x00000002, // TITLE Treat as ranged attack DESCRIPTION Use ammo, ranged attack range modifiers, ranged haste, etc.
		SPELL_ATTR0_ON_NEXT_SWING_NO_DAMAGE          = 0x00000004, // TITLE On next melee (type 1) DESCRIPTION Both "on next swing" attributes have identical handling in server & client
		SPELL_ATTR0_DO_NOT_LOG_IMMUNE_MISSES         = 0x00000008, // TITLE Replenishment (client only)
		SPELL_ATTR0_IS_ABILITY                       = 0x00000010, // TITLE Treat as ability DESCRIPTION Cannot be reflected, not affected by cast speed modifiers, etc.
		SPELL_ATTR0_IS_TRADESKILL                    = 0x00000020, // TITLE Trade skill recipe DESCRIPTION Displayed in recipe list, not affected by cast speed modifiers
		SPELL_ATTR0_PASSIVE                          = 0x00000040, // TITLE Passive spell DESCRIPTION Spell is automatically cast on self by core
		SPELL_ATTR0_DO_NOT_DISPLAY                   = 0x00000080, // TITLE Hidden in UI (client only) DESCRIPTION Not visible in spellbook or aura bar (Spellbook, Aura Icon, Combat Log)
		SPELL_ATTR0_DO_NOT_LOG                       = 0x00000100, // TITLE Hidden in combat log (client only) DESCRIPTION Spell will not appear in combat logs
		SPELL_ATTR0_HELD_ITEM_ONLY                   = 0x00000200, // TITLE Auto-target mainhand item (client only) DESCRIPTION Client will automatically select main-hand item as cast target
		SPELL_ATTR0_ON_NEXT_SWING                    = 0x00000400, // TITLE On next melee (type 2) DESCRIPTION Both "on next swing" attributes have identical handling in server & client
		SPELL_ATTR0_WEARER_CASTS_PROC_TRIGGER        = 0x00000800, // TITLE Unknown attribute 11@Attr0
		SPELL_ATTR0_SERVER_ONLY                      = 0x00001000, // TITLE Unused attribute 12@Attr0 DESCRIPTION not set in 3.3.5a
		SPELL_ATTR0_ALLOW_ITEM_SPELL_IN_PVP          = 0x00002000, // TITLE Only usable during nighttime
		SPELL_ATTR0_ONLY_INDOORS                     = 0x00004000, // TITLE Only usable indoors
		SPELL_ATTR0_ONLY_OUTDOORS                    = 0x00008000, // TITLE Only usable outdoors
		SPELL_ATTR0_NOT_SHAPESHIFTED                 = 0x00010000, // TITLE Not usable while shapeshifted
		SPELL_ATTR0_ONLY_STEALTHED                   = 0x00020000, // TITLE Only usable in stealth
		SPELL_ATTR0_DO_NOT_SHEATH                    = 0x00040000, // TITLE Don't shealthe weapons (client only)
		SPELL_ATTR0_SCALES_WITH_CREATURE_LEVEL       = 0x00080000, // TITLE Scale with caster level DESCRIPTION For non-player casts, scale impact and power cost with caster's level
		SPELL_ATTR0_CANCELS_AUTO_ATTACK_COMBAT       = 0x00100000, // TITLE Stop attacking after cast DESCRIPTION After casting this, the current auto-attack will be interrupted
		SPELL_ATTR0_NO_ACTIVE_DEFENSE                = 0x00200000, // TITLE Prevent physical avoidance DESCRIPTION Spell cannot be dodged, parried or blocked
		SPELL_ATTR0_TRACK_TARGET_IN_CAST_PLAYER_ONLY = 0x00400000, // TITLE Automatically face target during cast (client only)
		SPELL_ATTR0_ALLOW_CAST_WHILE_DEAD            = 0x00800000, // TITLE Can be cast while dead DESCRIPTION Spells without this flag cannot be cast by dead units in non-triggered contexts
		SPELL_ATTR0_ALLOW_WHILE_MOUNTED              = 0x01000000, // TITLE Can be cast while mounted
		SPELL_ATTR0_COOLDOWN_ON_EVENT                = 0x02000000, // TITLE Cooldown starts on expiry DESCRIPTION Spell is unusable while already active, and cooldown does not begin until the effects have worn off
		SPELL_ATTR0_AURA_IS_DEBUFF                   = 0x04000000, // TITLE Is negative spell DESCRIPTION Forces the spell to be treated as a negative spell
		SPELL_ATTR0_ALLOW_WHILE_SITTING              = 0x08000000, // TITLE Can be cast while sitting
		SPELL_ATTR0_NOT_IN_COMBAT_ONLY_PEACEFUL      = 0x10000000, // TITLE Cannot be used in combat
		SPELL_ATTR0_NO_IMMUNITIES                    = 0x20000000, // TITLE Pierce invulnerability DESCRIPTION Allows spell to pierce invulnerability, unless the invulnerability spell also has this attribute
		SPELL_ATTR0_HEARTBEAT_RESIST                 = 0x40000000, // TITLE Periodic resistance checks DESCRIPTION Periodically re-rolls against resistance to potentially expire aura early
		SPELL_ATTR0_NO_AURA_CANCEL                   = 0x80000000, // TITLE Aura cannot be cancelled DESCRIPTION Prevents the player from voluntarily canceling a positive aura
	}
	const enum SpellAttr1 {
		SPELL_ATTR1_DISMISS_PET_FIRST                        = 0x00000001, // TITLE Dismiss Pet on cast DESCRIPTION Without this attribute, summoning spells will fail if caster already has a pet
		SPELL_ATTR1_USE_ALL_MANA                             = 0x00000002, // TITLE Drain all power DESCRIPTION Ignores listed power cost and drains entire pool instead
		SPELL_ATTR1_IS_CHANNELED                             = 0x00000004, // TITLE Channeled (type 1) DESCRIPTION Both "channeled" attributes have identical handling in server & client
		SPELL_ATTR1_NO_REDIRECTION                           = 0x00000008, // TITLE Ignore redirection effects DESCRIPTION Spell will not be attracted by SPELL_MAGNET auras (Grounding Totem)
		SPELL_ATTR1_NO_SKILL_INCREASE                        = 0x00000010, // TITLE Unknown attribute 4@Attr1 DESCRIPTION stealth and whirlwind
		SPELL_ATTR1_ALLOW_WHILE_STEALTHED                    = 0x00000020, // TITLE Does not break stealth
		SPELL_ATTR1_IS_SELF_CHANNELED                        = 0x00000040, // TITLE Channeled (type 2) DESCRIPTION Both "channeled" attributes have identical handling in server & client
		SPELL_ATTR1_NO_REFLECTION                            = 0x00000080, // TITLE Ignore reflection effects DESCRIPTION Spell will pierce through Spell Reflection and similar
		SPELL_ATTR1_ONLY_PEACEFUL_TARGETS                    = 0x00000100, // TITLE Target cannot be in combat
		SPELL_ATTR1_INITIATE_COMBAT                          = 0x00000200, // TITLE Enables Auto-Attack (client only) DESCRIPTION Caster will begin auto-attacking the target on cast
		SPELL_ATTR1_NO_THREAT                                = 0x00000400, // TITLE Does not generate threat DESCRIPTION Also does not cause target to engage
		SPELL_ATTR1_AURA_UNIQUE                              = 0x00000800, // TITLE Aura will not refresh its duration when recast
		SPELL_ATTR1_FAILURE_BREAKS_STEALTH                   = 0x00001000, // TITLE Pickpocket (client only)
		SPELL_ATTR1_TOGGLE_FAR_SIGHT                         = 0x00002000, // TITLE Farsight aura (client only)
		SPELL_ATTR1_TRACK_TARGET_IN_CHANNEL                  = 0x00004000, // TITLE Track target while channeling DESCRIPTION While channeling, adjust facing to face target
		SPELL_ATTR1_IMMUNITY_PURGES_EFFECT                   = 0x00008000, // TITLE Immunity cancels preapplied auras DESCRIPTION For immunity spells, cancel all auras that this spell would make you immune to when the spell is applied
		SPELL_ATTR1_IMMUNITY_TO_HOSTILE_AND_FRIENDLY_EFFECTS = 0x00010000, // TITLE Immunity to Hostile & Friendly Effects DESCRIPTION Immunity applied by this aura will also be checked for friendly spells (school immunity only) - used by Cyclone for example to cause friendly spells and healing over time to be immune
		SPELL_ATTR1_NO_AUTOCAST_AI                           = 0x00020000, // TITLE Cannot be autocast by pet DESCRIPTION (AI)
		SPELL_ATTR1_PREVENTS_ANIM                            = 0x00040000, // TITLE NYI, auras apply UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT
		SPELL_ATTR1_EXCLUDE_CASTER                           = 0x00080000, // TITLE Cannot be self-cast
		SPELL_ATTR1_FINISHING_MOVE_DAMAGE                    = 0x00100000, // TITLE Requires combo points (type 1)
		SPELL_ATTR1_THREAT_ONLY_ON_MISS                      = 0x00200000, // TITLE Unknown attribute 21@Attr1
		SPELL_ATTR1_FINISHING_MOVE_DURATION                  = 0x00400000, // TITLE Requires combo points (type 2)
		SPELL_ATTR1_IGNORE_OWNERS_DEATH                      = 0x00800000, // TITLE Unknwon attribute 23@Attr1
		SPELL_ATTR1_SPECIAL_SKILLUP                          = 0x01000000, // TITLE Fishing (client only)
		SPELL_ATTR1_AURA_STAYS_AFTER_COMBAT                  = 0x02000000, // TITLE Aura stays after combat DESCRIPTION Aura will not be removed when the unit leaves combat
		SPELL_ATTR1_REQUIRE_ALL_TARGETS                      = 0x04000000, // TITLE Unknown attribute 26@Attr1 DESCRIPTION Related to [target=focus] and [target=mouseover] macros?
		SPELL_ATTR1_DISCOUNT_POWER_ON_MISS                   = 0x08000000, // TITLE Unknown attribute 27@Attr1 DESCRIPTION Melee spell?
		SPELL_ATTR1_NO_AURA_ICON                             = 0x10000000, // TITLE Hide in aura bar (client only)
		SPELL_ATTR1_NAME_IN_CHANNEL_BAR                      = 0x20000000, // TITLE Show spell name during channel (client only)
		SPELL_ATTR1_COMBO_ON_BLOCK                           = 0x40000000, // TITLE Enable at dodge DESCRIPTION (Mainline: Dispel All Stacks)
		SPELL_ATTR1_CAST_WHEN_LEARNED                        = 0x80000000, // TITLE Unknown attribute 31@Attr1
	}
	const enum SpellAttr2 {
		SPELL_ATTR2_ALLOW_DEAD_TARGET                    = 0x00000001, // TITLE Can target dead players or corpses
		SPELL_ATTR2_NO_SHAPESHIFT_UI                     = 0x00000002, // TITLE Unknown attribute 1@Attr2 DESCRIPTION vanish, shadowform, Ghost Wolf and other
		SPELL_ATTR2_IGNORE_LINE_OF_SIGHT                 = 0x00000004, // TITLE Ignore Line of Sight
		SPELL_ATTR2_ALLOW_LOW_LEVEL_BUFF                 = 0x00000008, // TITLE Ignore aura scaling
		SPELL_ATTR2_USE_SHAPESHIFT_BAR                   = 0x00000010, // TITLE Show in stance bar (client only)
		SPELL_ATTR2_AUTO_REPEAT                          = 0x00000020, // TITLE Ranged auto-attack spell
		SPELL_ATTR2_CANNOT_CAST_ON_TAPPED                = 0x00000040, // TITLE Cannot target others' tapped units DESCRIPTION Can only target untapped units, or those tapped by caster
		SPELL_ATTR2_DO_NOT_REPORT_SPELL_FAILURE          = 0x00000080, // TITLE Unknown attribute 7@Attr2
		SPELL_ATTR2_INCLUDE_IN_ADVANCED_COMBAT_LOG       = 0x00000100, // TITLE Unused attribute 8@Attr2 DESCRIPTION not set in 3.3.5a
		SPELL_ATTR2_ALWAYS_CAST_AS_UNIT                  = 0x00000200, // TITLE Unknown attribute 9@Attr2
		SPELL_ATTR2_SPECIAL_TAMING_FLAG                  = 0x00000400, // TITLE Unknown attribute 10@Attr2 DESCRIPTION Related to taming?
		SPELL_ATTR2_NO_TARGET_PER_SECOND_COST            = 0x00000800, // TITLE Health Funnel
		SPELL_ATTR2_CHAIN_FROM_CASTER                    = 0x00001000, // TITLE Chain from caster DESCRIPTION Cleave, Heart Strike, Maul, Sunder Armor, Swipe
		SPELL_ATTR2_ENCHANT_OWN_ITEM_ONLY                = 0x00002000, // TITLE Enchant persists when entering arena
		SPELL_ATTR2_ALLOW_WHILE_INVISIBLE                = 0x00004000, // TITLE Unknown attribute 14@Attr2
		SPELL_ATTR2_DO_NOT_CONSUME_IF_GAINED_DURING_CAST = 0x00008000, // TITLE Unused attribute 15@Attr2 DESCRIPTION not set in 3.3.5a
		SPELL_ATTR2_NO_ACTIVE_PETS                       = 0x00010000, // TITLE Tame Beast
		SPELL_ATTR2_DO_NOT_RESET_COMBAT_TIMERS           = 0x00020000, // TITLE Don't reset swing timer DESCRIPTION Does not reset melee/ranged autoattack timer on cast
		SPELL_ATTR2_NO_JUMP_WHILE_CAST_PENDING           = 0x00040000, // TITLE Requires dead pet
		SPELL_ATTR2_ALLOW_WHILE_NOT_SHAPESHIFTED         = 0x00080000, // TITLE Also allow outside shapeshift (caster form) DESCRIPTION Even if Stances are nonzero, allow spell to be cast outside of shapeshift (though not in a different shapeshift)
		SPELL_ATTR2_INITIATE_COMBAT_POST_CAST            = 0x00100000, // TITLE (Enables Auto-Attack)
		SPELL_ATTR2_FAIL_ON_ALL_TARGETS_IMMUNE           = 0x00200000, // TITLE Damage reduction ability DESCRIPTION Causes BG flags to be dropped if combined with ATTR1_DISPEL_AURAS_ON_IMMUNITY
		SPELL_ATTR2_NO_INITIAL_THREAD                    = 0x00400000, // TITLE Unknown attribute 22@Attr2 DESCRIPTION Ambush, Backstab, Cheap Shot, Death Grip, Garrote, Judgements, Mutilate, Pounce, Ravage, Shiv, Shred
		SPELL_ATTR2_PROC_COOLDOWN_ON_FAILURE             = 0x00800000, // TITLE Proc Cooldown On Failure
		SPELL_ATTR2_ITEM_CAST_WITH_OWNER_SKILL           = 0x01000000, // TITLE Unknown attribute 24@Attr2
		SPELL_ATTR2_DONT_BLOCK_MANA_REGEN                = 0x02000000, // TITLE Unknown attribute 25@Attr2
		SPELL_ATTR2_NO_SCHOOL_IMMUNITIES                 = 0x04000000, // TITLE Pierce aura application immunities DESCRIPTION Allow aura to be applied despite target being immune to new aura applications
		SPELL_ATTR2_IGNORE_WEAPONSKILL                   = 0x08000000, // TITLE Unknown attribute 27@Attr2
		SPELL_ATTR2_NOT_AN_ACTION                        = 0x10000000, // TITLE Unknown attribute 28@Attr2
		SPELL_ATTR2_CANT_CRIT                            = 0x20000000, // TITLE Cannot critically strike
		SPELL_ATTR2_ACTIVE_THREAT                        = 0x40000000, // TITLE Allow triggered spell to trigger (type 1) DESCRIPTION Without this attribute, any triggered spell will be unable to trigger other auras' procs
		SPELL_ATTR2_RETAIN_ITEM_CAST                     = 0x80000000, // TITLE Food buff (client only)
	}
	const enum SpellAttr3 {
		SPELL_ATTR3_PVP_ENABLING                          = 0x00000001, // TITLE Unknown attribute 0@Attr3
		SPELL_ATTR3_NO_PROC_EQUIP_REQUIREMENT             = 0x00000002, // TITLE 1 Ignores subclass mask check when checking proc
		SPELL_ATTR3_NO_CASTING_BAR_TEXT                   = 0x00000004, // TITLE Unknown attribute 2@Attr3
		SPELL_ATTR3_COMPLETELY_BLOCKED                    = 0x00000008, // TITLE Blockable spell
		SPELL_ATTR3_NO_RES_TIMER                          = 0x00000010, // TITLE Ignore resurrection timer
		SPELL_ATTR3_NO_DURABILITY_LOSS                    = 0x00000020, // TITLE Unknown attribute 5@Attr3
		SPELL_ATTR3_NO_AVOIDANCE                          = 0x00000040, // TITLE Unknown attribute 6@Attr3
		SPELL_ATTR3_DOT_STACKING_RULE                     = 0x00000080, // TITLE Stack separately for each caster
		SPELL_ATTR3_ONLY_ON_PLAYER                        = 0x00000100, // TITLE Can only target players
		SPELL_ATTR3_NOT_A_PROC                            = 0x00000200, // TITLE Allow triggered spell to trigger (type 2) DESCRIPTION Without this attribute, any triggered spell will be unable to trigger other auras' procs
		SPELL_ATTR3_REQUIRES_MAIN_HAND_WEAPON             = 0x00000400, // TITLE Require main hand weapon
		SPELL_ATTR3_ONLY_BATTLEGROUNDS                    = 0x00000800, // TITLE Can only be cast in battleground
		SPELL_ATTR3_ONLY_ON_GHOSTS                        = 0x00001000, // TITLE Can only target ghost players
		SPELL_ATTR3_HIDE_CHANNEL_BAR                      = 0x00002000, // TITLE Do not display channel bar (client only)
		SPELL_ATTR3_HIDE_IN_RAID_FILTER                   = 0x00004000, // TITLE Honorless Target
		SPELL_ATTR3_NORMAL_RANGED_ATTACK                  = 0x00008000, // TITLE Unknown attribute 15@Attr3 DESCRIPTION Auto Shoot, Shoot, Throw - ranged normal attack attribute?
		SPELL_ATTR3_SUPPRESS_CASTER_PROCS                 = 0x00010000, // TITLE Cannot trigger procs
		SPELL_ATTR3_SUPPRESS_TARGET_PROCS                 = 0x00020000, // TITLE No initial aggro
		SPELL_ATTR3_ALWAYS_HIT                            = 0x00040000, // TITLE Ignore hit result DESCRIPTION Spell cannot miss, or be dodged/parried/blocked
		SPELL_ATTR3_INSTANT_TARGET_PROCS                  = 0x00080000, // TITLE Cannot trigger spells during aura proc
		SPELL_ATTR3_ALLOW_AURA_WHILE_DEAD                 = 0x00100000, // TITLE Persists through death
		SPELL_ATTR3_ONLY_PROC_OUTDOORS                    = 0x00200000, // TITLE Unused attribute 21@Attr3 DESCRIPTION Not set in 3.3.5a
		SPELL_ATTR3_CASTING_CANCELS_AUTOREPEAT            = 0x00400000, // TITLE Unused attribute 22@Attr3 DESCRIPTION Not set in 3.3.5a
		SPELL_ATTR3_NO_DAMAGE_HISTORY                     = 0x00800000, // TITLE Unknown attribute 23@Attr3
		SPELL_ATTR3_REQUIRES_OFF_HAND_WEAPON              = 0x01000000, // TITLE Requires offhand weapon
		SPELL_ATTR3_TREAT_AS_PERIODIC                     = 0x02000000, // TITLE Treat as periodic effect
		SPELL_ATTR3_CAN_PROC_FROM_PROCS                   = 0x04000000, // TITLE Can trigger from triggered spells
		SPELL_ATTR3_ONLY_PROC_ON_CASTER                   = 0x08000000, // TITLE Drain Soul
		SPELL_ATTR3_IGNORE_CASTER_AND_TARGET_RESTRICTIONS = 0x10000000, // TITLE Unknown attribute 28@Attr3
		SPELL_ATTR3_IGNORE_CASTER_MODIFIERS               = 0x20000000, // TITLE Damage dealt is unaffected by modifiers
		SPELL_ATTR3_DO_NOT_DISPLAY_RANGE                  = 0x40000000, // TITLE Do not show range in tooltip (client only)
		SPELL_ATTR3_NOT_ON_AOE_IMMUNE                     = 0x80000000, // TITLE Unknown attribute 31@Attr3
	}
	const enum SpellAttr4 {
		SPELL_ATTR4_NO_CAST_LOG                        = 0x00000001, // TITLE Cannot be resisted
		SPELL_ATTR4_CLASS_TRIGGER_ONLY_ON_TARGET       = 0x00000002, // TITLE Only proc on self-cast
		SPELL_ATTR4_AURA_EXPIRES_OFFLINE               = 0x00000004, // TITLE Buff expires while offline DESCRIPTION Debuffs (except Resurrection Sickness) will automatically do this
		SPELL_ATTR4_NO_HELPFUL_THREAT                  = 0x00000008, // TITLE Unknown attribute 3@Attr4
		SPELL_ATTR4_NO_HARMFUL_THREAT                  = 0x00000010, // TITLE Treat as delayed spell DESCRIPTION This will no longer cause guards to attack on use??
		SPELL_ATTR4_ALLOW_CLIENT_TARGETING             = 0x00000020, // TITLE Unknown attribute 5@Attr4
		SPELL_ATTR4_CANNOT_BE_STOLEN                   = 0x00000040, // TITLE Aura cannot be stolen
		SPELL_ATTR4_ALLOW_CAST_WHILE_CASTING           = 0x00000080, // TITLE Can be cast while casting DESCRIPTION Ignores already in-progress cast and still casts
		SPELL_ATTR4_IGNORE_DAMAGE_TAKEN_MODIFIERS      = 0x00000100, // TITLE Deals fixed damage
		SPELL_ATTR4_COMBAT_FEEDBACK_WHEN_USABLE        = 0x00000200, // TITLE Spell is initially disabled (client only)
		SPELL_ATTR4_WEAPON_SPEED_COST_SCALING          = 0x00000400, // TITLE Attack speed modifies cost DESCRIPTION Adds 10 to power cost for each 1s of weapon speed
		SPELL_ATTR4_NO_PARTIAL_IMMUNITY                = 0x00000800, // TITLE Unknown attribute 11@Attr4
		SPELL_ATTR4_AURA_IS_BUFF                       = 0x00001000, // TITLE Unknown attribute 12@Attr4
		SPELL_ATTR4_DO_NOT_LOG_CASTER                  = 0x00002000, // TITLE Unknown attribute 13@Attr4
		SPELL_ATTR4_DAMAGE_DOESNT_BREAK_AURAS          = 0x00004000, // TITLE Damage does not break auras
		SPELL_ATTR4_NOT_IN_SPELLBOOK                   = 0x00008000, // TITLE Unknown attribute 15@Attr4
		SPELL_ATTR4_NOT_IN_ARENA_OR_RATED_BATTLEGROUND = 0x00010000, // TITLE Not usable in arena DESCRIPTION Makes spell unusable despite CD <= 10min
		SPELL_ATTR4_IGNORE_DEFAULT_ARENA_RESTRICTIONS  = 0x00020000, // TITLE Usable in arena DESCRIPTION Makes spell usable despite CD > 10min
		SPELL_ATTR4_BOUNCY_CHAIN_MISSILES              = 0x00040000, // TITLE Chain area targets DESCRIPTION [NYI] Hits area targets over time instead of all at once
		SPELL_ATTR4_ALLOW_PROC_WHILE_SITTING           = 0x00080000, // TITLE Unknown attribute 19@Attr4 DESCRIPTION proc dalayed, after damage or don't proc on absorb?
		SPELL_ATTR4_AURA_NEVER_BOUNCES                 = 0x00100000, // TITLE Allow self-cast to override stronger aura (client only)
		SPELL_ATTR4_ALLOW_ENETRING_ARENA               = 0x00200000, // TITLE Keep when entering arena
		SPELL_ATTR4_PROC_SUPPRESS_SWING_ANIM           = 0x00400000, // TITLE Unknown attribute 22@Attr4 DESCRIPTION Seal of Command (42058,57770) and Gymer's Smash 55426
		SPELL_ATTR4_SUPPRESS_WEAPON_PROCS               = 0x00800000, // TITLE Cannot trigger item spells
		SPELL_ATTR4_AUTO_RANGED_COMBAT                 = 0x01000000, // TITLE Unknown attribute 24@Attr4 DESCRIPTION Shoot-type spell?
		SPELL_ATTR4_OWNER_POWER_SCALING                = 0x02000000, // TITLE Pet Scaling aura
		SPELL_ATTR4_ONLY_FLYING_AREAS                  = 0x04000000, // TITLE Only in Outland/Northrend
		SPELL_ATTR4_FORCE_DISPLAY_CASTBAR              = 0x08000000, // TITLE Inherit critical chance from triggering aura
		SPELL_ATTR4_IGNORE_COMBAT_TIMERS               = 0x10000000, // TITLE Unknown attribute 28@Attr4 DESCRIPTION Aimed Shot
		SPELL_ATTR4_AURA_BOUNCE_FAILS_SPELL            = 0x20000000, // TITLE Unknown attribute 29@Attr4
		SPELL_ATTR4_OBSOLETE                           = 0x40000000, // TITLE Unknown attribute 30@Attr4
		SPELL_ATTR4_USE_FACING_FROM_SPELL              = 0x80000000, // TITLE Unknown attribute 31@Attr4 DESCRIPTION Polymorph (chicken) 228 and Sonic Boom (38052,38488)
	}
	const enum SpellAttr5 {
		SPELL_ATTR5_ALLOW_ACTION_DURING_CHANNEL                    = 0x00000001, // TITLE Can be channeled while moving/casting
		SPELL_ATTR5_NO_REAGENT_COST_WITH_AURA                      = 0x00000002, // TITLE No reagents during arena preparation
		SPELL_ATTR5_REMOVE_ENTERING_ARENA                          = 0x00000004, // TITLE Remove when entering arena DESCRIPTION Force this aura to be removed on entering arena, regardless of other properties
		SPELL_ATTR5_ALLOW_WHILE_STUNNED                            = 0x00000008, // TITLE Usable while stunned
		SPELL_ATTR5_TRIGGERS_CHANNELING                            = 0x00000010, // TITLE Unknown attribute 4@Attr5
		SPELL_ATTR5_LIMIT_N                                        = 0x00000020, // TITLE Single-target aura DESCRIPTION Remove previous application to another unit if applied
		SPELL_ATTR5_IGNORE_AREA_EFFECT_PVP_CHECK                   = 0x00000040, // TITLE Unknown attribute 6@Attr5
		SPELL_ATTR5_NOT_ON_PLAYER                                  = 0x00000080, // TITLE Cannot target players
		SPELL_ATTR5_NOT_ON_PLAYER_CONTROLLED_NPC                   = 0x00000100, // TITLE Cannot target player controlled units but can target players
		SPELL_ATTR5_EXTRA_INITIAL_PERIOD                           = 0x00000200, // TITLE Immediately do periodic tick on apply
		SPELL_ATTR5_DO_NOT_DISPLAY_DURATION                        = 0x00000400, // TITLE Do not send aura duration to client
		SPELL_ATTR5_IMPLIED_TARGETING                              = 0x00000800, // TITLE Auto-target target of target (client only)
		SPELL_ATTR5_MELEE_CHAIN_TARGETING                          = 0x00001000, // TITLE Unknown attribute 12@Attr5 DESCRIPTION Cleave related?
		SPELL_ATTR5_SPELL_HASTE_AFFECTS_PERIODIC                   = 0x00002000, // TITLE Duration scales with Haste Rating
		SPELL_ATTR5_NOT_AVALIABLE_WHILE_CHARMED                    = 0x00004000, // TITLE Charmed units cannot cast this spell
		SPELL_ATTR5_TREAT_AS_AREA_EFFECT                           = 0x00008000, // TITLE Unknown attribute 15@Attr5 DESCRIPTION Related to multi-target spells?
		SPELL_ATTR5_AURA_AFFECTS_NOT_JUST_REQ_EQUIPPED_ITEM        = 0x00010000, // TITLE DESCRIPTION this allows spells with EquippedItemClass to affect spells from other items if the required item is equipped
		SPELL_ATTR5_ALLOW_WHILE_FLEEING                            = 0x00020000, // TITLE Usable while feared
		SPELL_ATTR5_ALLOW_WHILE_CONFUSED                           = 0x00040000, // TITLE Usable while confused
		SPELL_ATTR5_AI_DOESNT_FACE_TARGET                          = 0x00080000, // TITLE Do not auto-turn while casting
		SPELL_ATTR5_DO_NOT_ATTEMPT_A_PET_RESUMMON_WHEN_DISMOUNTING = 0x00100000, // TITLE Unknown attribute 20@Attr5
		SPELL_ATTR5_IGNORE_TARGET_REQUIREMENTS                     = 0x00200000, // TITLE Unknown attribute 21@Attr5
		SPELL_ATTR5_NOT_ON_TRIVIAL                                 = 0x00400000, // TITLE Unknown attribute 22@Attr5
		SPELL_ATTR5_NO_PARTIAL_RESISTS                             = 0x00800000, // TITLE Unknown attribute 23@Attr5
		SPELL_ATTR5_IGNORE_CASTER_REQUIREMENETS                    = 0x01000000, // TITLE Unknown attribute 24@Attr5
		SPELL_ATTR5_ALWAYS_LINE_OF_SIGHT                           = 0x02000000, // TITLE Unknown attribute 25@Attr5
		SPELL_ATTR5_ALWAYS_AOE_LINE_OF_SIGHT                       = 0x04000000, // TITLE Ignore line of sight checks
		SPELL_ATTR5_NO_CASTER_AURA_ICON                            = 0x08000000, // TITLE Don't show aura if self-cast (client only)
		SPELL_ATTR5_NO_TARGET_AURA_ICON                            = 0x10000000, // TITLE Don't show aura unless self-cast (client only)
		SPELL_ATTR5_AURA_UNIQUE_PER_CASTER                         = 0x20000000, // TITLE Unknown attribute 29@Attr5
		SPELL_ATTR5_ALWAYS_SHOW_GROUND_TEXTURE                     = 0x40000000, // TITLE Unknown attribute 30@Attr5
		SPELL_ATTR5_ADD_MELEE_HIT_RATING                           = 0x80000000, // TITLE Unknown attribute 31@Attr5 DESCRIPTION Forces nearby enemies to attack caster?
	}
	const enum SpellAttr6 {
		SPELL_ATTR6_NO_COOLDOWN_ON_TOOLTIP                     = 0x00000001, // TITLE Don't display cooldown (client only)
		SPELL_ATTR6_DO_NOT_RESET_COOLDOWN_IN_ARENA             = 0x00000002, // TITLE Only usable in arena
		SPELL_ATTR6_NOT_AN_ATTACK                              = 0x00000004, // TITLE Ignore all preventing caster auras
		SPELL_ATTR6_CAN_ASSIST_IMMUNE_PC                       = 0x00000008, // TITLE Ignore immunity flags when assisting
		SPELL_ATTR6_IGNORE_FOR_MOD_TIME_RATE                   = 0x00000010, // TITLE Unknown attribute 4@Attr6
		SPELL_ATTR6_DO_NOT_CONSUME_RESOURCES                   = 0x00000020, // TITLE Don't consume proc charges
		SPELL_ATTR6_FLOATING_COMBAT_TEXT_ON_CAST               = 0x00000040, // TITLE Generate spell_cast event instead of aura_start (client only)
		SPELL_ATTR6_AURA_IS_WEAPON_PROC                        = 0x00000080, // TITLE Unknown attribute 7@Attr6
		SPELL_ATTR6_DO_NOT_CHAIN_TO_CROWD_CONTROLLED_TARGETS   = 0x00000100, // TITLE Do not implicitly target in CC DESCRIPTION Implicit targeting (chaining and area targeting) will not impact crowd controlled targets
		SPELL_ATTR6_ALLOW_ON_CHARMED_TARGETS                   = 0x00000200, // TITLE Unknown attribute 9@Attr6
		SPELL_ATTR6_NO_AURA_LOG                                = 0x00000400, // TITLE Can target possessed friends DESCRIPTION [NYI]
		SPELL_ATTR6_NOT_IN_RAID_INSTANCES                      = 0x00000800, // TITLE Unusable in raid instances
		SPELL_ATTR6_ALLOW_WHILE_RIDING_VEHICLE                 = 0x00001000, // TITLE Castable while caster is on vehicle
		SPELL_ATTR6_IGNORE_PHASE_SHIFT                         = 0x00002000, // TITLE Can target invisible units
		SPELL_ATTR6_AI_PRIMARY_RANGED_ATTACK                   = 0x00004000, // TITLE Unknown attribute 14@Attr6
		SPELL_ATTR6_NO_PUSHBACK                                = 0x00008000, // TITLE Not affected by pushback DESCRIPTION Casts/Channels will not affected by pushback
		SPELL_ATTR6_NO_JUMP_PATHING                            = 0x00010000, // TITLE Unknown attribute 16@Attr6
		SPELL_ATTR6_ALLOW_EQUIP_WHILE_CASTING                  = 0x00020000, // TITLE Unknown attribute 17@Attr6 DESCRIPTION Mount related?
		SPELL_ATTR6_ORIGINATE_FROM_CONTROLLER                  = 0x00040000, // TITLE Spell is cast by charmer DESCRIPTION Client will prevent casting if not possessed, charmer will be caster for all intents and purposes
		SPELL_ATTR6_DELAY_COMBAT_TIMER_DURING_CAST             = 0x00080000, // TITLE Unknown attribute 19@Attr6 DESCRIPTION only 47488, 50782
		SPELL_ATTR6_AURA_ICON_ONLY_FOR_CASTER                  = 0x00100000, // TITLE Only visible to caster (client only) (LIMIT 10)
		SPELL_ATTR6_SHOW_MECHANIC_AS_COMBAT_TEXT               = 0x00200000, // TITLE Client UI target effects (client only)
		SPELL_ATTR6_ABSORB_CANNOT_BE_IGNORED                   = 0x00400000, // TITLE Unknown attribute 22@Attr6 DESCRIPTION only 72054
		SPELL_ATTR6_TAPS_IMMEDIATELY                           = 0x00800000, // TITLE Unknown attribute 23@Attr6
		SPELL_ATTR6_CAN_TARGET_UNTARGETABLE                    = 0x01000000, // TITLE Can target untargetable units
		SPELL_ATTR6_DOESNT_RESET_SWING_TIMER_IF_INSTANT        = 0x02000000, // TITLE Do not reset swing timer if cast time is instant
		SPELL_ATTR6_VEHICLE_IMMUNITY_CATEGORY                  = 0x04000000, // TITLE Unknown attribute 26@Attr6 DESCRIPTION Player castable buff?
		SPELL_ATTR6_IGNORE_HEALTH_MODIFIERS                    = 0x08000000, // TITLE Limit applicable %healing modifiers DESCRIPTION This prevents certain healing modifiers from applying - see implementation if you really care about details
		SPELL_ATTR6_DO_NOT_SELECT_TARGET_WITH_INITIATES_COMBAT = 0x10000000, // TITLE Unknown attribute 28@Attr6 DESCRIPTION Death grip?
		SPELL_ATTR6_IGNORE_CASTER_DAMAGE_MODIFIERS             = 0x20000000, // TITLE Limit applicable %damage modifiers DESCRIPTION This prevents certain damage modifiers from applying - see implementation if you really care about details
		SPELL_ATTR6_DISABLE_TIED_EFFECT_POINTS                 = 0x40000000, // TITLE Unknown attribute 30@Attr6
		SPELL_ATTR6_NO_CATEGORY_COOLDOWN_MODS                  = 0x80000000, // TITLE Ignore cooldown modifiers for category cooldown
	}
	const enum SpellAttr7 {
		SPELL_ATTR7_ALLOW_SPELL_REFLECTION                        = 0x00000001, // TITLE Unknown attribute 0@Attr7 DESCRIPTION Shaman's new spells (Call of the ...), Feign Death.
		SPELL_ATTR7_NO_TARGET_DURATION_MOD                        = 0x00000002, // TITLE Ignore duration modifiers
		SPELL_ATTR7_DISABLE_AURA_WHILE_DEAD                       = 0x00000004, // TITLE Reactivate at resurrect (client only)
		SPELL_ATTR7_DEBUG_SPELL                                   = 0x00000008, // TITLE Is cheat spell DESCRIPTION Cannot cast if caster doesn't have UnitFlag2 & UNIT_FLAG2_ALLOW_CHEAT_SPELLS
		SPELL_ATTR7_TREAT_AS_RAID_BUFF                            = 0x00000010, // TITLE Unknown attribute 4@Attr7 DESCRIPTION Soulstone related?
		SPELL_ATTR7_CAN_BE_MULTI_CAST                             = 0x00000020, // TITLE Summons player-owned totem
		SPELL_ATTR7_DONT_CAUSE_SPELL_PUSHBACK                     = 0x00000040, // TITLE Damage dealt by this does not cause spell pushback
		SPELL_ATTR7_PREPARE_FOR_VEHICLE_CONTROL_END               = 0x00000080, // TITLE Unknown attribute 7@Attr7 DESCRIPTION 66218 (Launch) spell.
		SPELL_ATTR7_HORDE_SPECIFIC_SPELL                          = 0x00000100, // TITLE Horde only
		SPELL_ATTR7_ALLIANCE_SPECIFIC_SPELL                       = 0x00000200, // TITLE Alliance only
		SPELL_ATTR7_DISPEL_REMOVES_CHARGES                        = 0x00000400, // TITLE Dispel/Spellsteal remove individual charges
		SPELL_ATTR7_CAN_CAUSE_INTERRUPT                           = 0x00000800, // TITLE Only interrupt non-player casting
		SPELL_ATTR7_CAN_CAUSE_SILENCE                             = 0x00001000, // TITLE Unused attribute 12@Attr7 DESCRIPTION Not set in 3.3.5a.
		SPELL_ATTR7_NO_UI_NOT_INTERRUPTIBLE                       = 0x00002000, // TITLE Unused attribute 13@Attr7 DESCRIPTION Not set in 3.3.5a.
		SPELL_ATTR7_RECAST_ON_RESUMMON                            = 0x00004000, // TITLE Unknown attribute 14@Attr7 DESCRIPTION Only 52150 (Raise Dead - Pet) spell.
		SPELL_ATTR7_RESET_SWING_TIMER_AT_SPELL_START              = 0x00008000, // TITLE Unknown attribute 15@Attr7 DESCRIPTION Exorcism - guaranteed crit vs families?
		SPELL_ATTR7_ONLY_IN_SPELLBOOK_UNTIL_LEARNED               = 0x00010000, // TITLE Can restore secondary power DESCRIPTION Only spells with this attribute can replenish a non-active power type
		SPELL_ATTR7_DO_NOT_LOG_PVP_KILL                           = 0x00020000, // TITLE Unknown attribute 17@Attr7 DESCRIPTION Only 27965 (Suicide) spell.
		SPELL_ATTR7_ATTACK_ON_CHARGE_TO_UNIT                      = 0x00040000, // TITLE Has charge effect
		SPELL_ATTR7_REPORT_SPELL_FAILURE_TO_UNIT_TARGET           = 0x00080000, // TITLE Is zone teleport
		SPELL_ATTR7_NO_CLIENT_FAIL_WHILE_STUNNED_FLEEING_CONFUSED = 0x00100000, // TITLE Unknown attribute 20@Attr7 DESCRIPTION Invulnerability related?
		SPELL_ATTR7_RETAIN_COOLDOWN_THROUGH_LOAD                  = 0x00200000, // TITLE Unused attribute 21@Attr7 DESCRPIPTION Not set in 3.3.5a
		SPELL_ATTR7_IGNORES_COLD_WEATHER_FLYING_REQUIREMENT       = 0x00400000, // TITLE Ignore cold weather flying restriction DESCRIPTION Set for loaner mounts, allows them to be used despite lacking required flight skill
		SPELL_ATTR7_NO_ATTACK_DODGE                               = 0x00800000, // TITLE Spell cannot be dodged 23@Attr7 DESCRIPTION Motivate, Mutilate, Shattering Throw
		SPELL_ATTR7_NO_ATTACK_PARRY                               = 0x01000000, // TITLE Spell cannot be parried 24@Attr7 DESCRIPTION Motivate, Mutilate, Perform Speech, Shattering Throw
		SPELL_ATTR7_NO_ATTACK_MISS                                = 0x02000000, // TITLE Spell cannot be missed 25@Attr7
		SPELL_ATTR7_TREAT_AS_NPC_AOE                              = 0x04000000, // TITLE Treat as NPC AoE
		SPELL_ATTR7_BYPASS_NO_RESURRECTION_AURA                   = 0x08000000, // TITLE Bypasses the prevent resurrection aura
		SPELL_ATTR7_DO_NOT_COUNT_FOR_PVP_SCOREBOARD               = 0x10000000, // TITLE Consolidate in raid buff frame (client only)
		SPELL_ATTR7_REFLECTION_ONLY_DEFENDS                       = 0x20000000, // TITLE Unknown attribute 29@Attr7 DESCRIPTION only 69028, 71237
		SPELL_ATTR7_CAN_PROC_FROM_SUPPRESSED_TARGET_PROCS         = 0x40000000, // TITLE Unknown attribute 30@Attr7 DESCRIPTION Burning Determination, Divine Sacrifice, Earth Shield, Prayer of Mending
		SPELL_ATTR7_ALWAYS_CAST_LOG                               = 0x80000000, // TITLE Client indicator (client only)
	}
	const enum SpellCustomAttributes {
		SPELL_ATTR0_CU_ENCHANT_PROC                  = 0x00000001,
		SPELL_ATTR0_CU_CONE_BACK                     = 0x00000002,
		SPELL_ATTR0_CU_CONE_LINE                     = 0x00000004,
		SPELL_ATTR0_CU_SHARE_DAMAGE                  = 0x00000008,
		SPELL_ATTR0_CU_NO_INITIAL_THREAT             = 0x00000010,
		SPELL_ATTR0_CU_AURA_CC                       = 0x00000020,
		SPELL_ATTR0_CU_DONT_BREAK_STEALTH            = 0x00000040,
		SPELL_ATTR0_CU_NO_PVP_FLAG                   = 0x00000080,
		SPELL_ATTR0_CU_DIRECT_DAMAGE                 = 0x00000100,
		SPELL_ATTR0_CU_CHARGE                        = 0x00000200,
		SPELL_ATTR0_CU_PICKPOCKET                    = 0x00000400,
		SPELL_ATTR0_CU_IGNORE_EVADE                  = 0x00000800,
		SPELL_ATTR0_CU_NEGATIVE_EFF0                 = 0x00001000,
		SPELL_ATTR0_CU_NEGATIVE_EFF1                 = 0x00002000,
		SPELL_ATTR0_CU_NEGATIVE_EFF2                 = 0x00004000,
		SPELL_ATTR0_CU_IGNORE_ARMOR                  = 0x00008000,
		SPELL_ATTR0_CU_REQ_TARGET_FACING_CASTER      = 0x00010000,
		SPELL_ATTR0_CU_REQ_CASTER_BEHIND_TARGET      = 0x00020000,
		SPELL_ATTR0_CU_ALLOW_INFLIGHT_TARGET         = 0x00040000,
		SPELL_ATTR0_CU_NEEDS_AMMO_DATA               = 0x00080000,
		SPELL_ATTR0_CU_BINARY_SPELL                  = 0x00100000,
		SPELL_ATTR0_CU_NO_POSITIVE_TAKEN_BONUS       = 0x00200000,
		SPELL_ATTR0_CU_SINGLE_AURA_STACK             = 0x00400000,
		SPELL_ATTR0_CU_SCHOOLMASK_NORMAL_WITH_MAGIC  = 0x00800000,
		SPELL_ATTR0_CU_AURA_CANNOT_BE_SAVED          = 0x01000000,
		SPELL_ATTR0_CU_POSITIVE_EFF0                 = 0x02000000,
		SPELL_ATTR0_CU_POSITIVE_EFF1                 = 0x04000000,
		SPELL_ATTR0_CU_POSITIVE_EFF2                 = 0x08000000,
		SPELL_ATTR0_CU_FORCE_SEND_CATEGORY_COOLDOWNS = 0x10000000,
		SPELL_ATTR0_CU_FORCE_AURA_SAVING             = 0x20000800,
		SPELL_ATTR0_CU_ONLY_ONE_AREA_AURA            = 0x20000000,
		SPELL_ATTR0_CU_ENCOUNTER_REWARD              = 0x40000000,
		SPELL_ATTR0_CU_BYPASS_MECHANIC_IMMUNITY      = 0x80000000,

		SPELL_ATTR0_CU_NEGATIVE                      = SPELL_ATTR0_CU_NEGATIVE_EFF0 | SPELL_ATTR0_CU_NEGATIVE_EFF1 | SPELL_ATTR0_CU_NEGATIVE_EFF2,
		SPELL_ATTR0_CU_POSITIVE                      = SPELL_ATTR0_CU_POSITIVE_EFF0 | SPELL_ATTR0_CU_POSITIVE_EFF1 | SPELL_ATTR0_CU_POSITIVE_EFF2,
	}
}
export {};
