declare global {
	const enum SpellTargetCheckTypes {
		TARGET_CHECK_DEFAULT,
		TARGET_CHECK_ENTRY,
		TARGET_CHECK_ENEMY,
		TARGET_CHECK_ALLY,
		TARGET_CHECK_PARTY,
		TARGET_CHECK_RAID,
		TARGET_CHECK_RAID_CLASS,
		TARGET_CHECK_PASSENGER,
		TARGET_CHECK_CORPSE,
	}
}
export {};
