declare global {
	const enum SpellValueMod {
		SPELLVALUE_BASE_POINT0,
		SPELLVALUE_BASE_POINT1,
		SPELLVALUE_BASE_POINT2,
		SPELLVALUE_RADIUS_MOD,
		SPELLVALUE_MAX_TARGETS,
		SPELLVALUE_AURA_STACK,
		SPELLVALUE_AURA_DURATION,
		SPELLVALUE_FORCED_CRIT_RESULT,
		SPELLVALUE_MISCVALUE0,
		SPELLVALUE_MISCVALUE1,
		SPELLVALUE_MISCVALUE2,
	}
}
export {};
