declare global {
	const enum SpellTargetObjectTypes {
		TARGET_OBJECT_TYPE_NONE = 0,
		TARGET_OBJECT_TYPE_SRC,
		TARGET_OBJECT_TYPE_DEST,
		TARGET_OBJECT_TYPE_UNIT,
		TARGET_OBJECT_TYPE_UNIT_AND_DEST,
		TARGET_OBJECT_TYPE_GOBJ,
		TARGET_OBJECT_TYPE_GOBJ_ITEM,
		TARGET_OBJECT_TYPE_ITEM,
		TARGET_OBJECT_TYPE_CORPSE,
		// only for effect target type
		TARGET_OBJECT_TYPE_CORPSE_ENEMY,
		TARGET_OBJECT_TYPE_CORPSE_ALLY,
	}
}
export {};
