declare global {
	const enum UnitMods {
		UNIT_MOD_STAT_STRENGTH,                                 // UNIT_MOD_STAT_STRENGTH..UNIT_MOD_STAT_SPIRIT must be in existed order, it's accessed by index values of Stats enum.
		UNIT_MOD_STAT_AGILITY,
		UNIT_MOD_STAT_STAMINA,
		UNIT_MOD_STAT_INTELLECT,
		UNIT_MOD_STAT_SPIRIT,
		UNIT_MOD_HEALTH,
		UNIT_MOD_MANA,                                          // UNIT_MOD_MANA..UNIT_MOD_RUNIC_POWER must be in existed order, it's accessed by index values of Powers enum.
		UNIT_MOD_RAGE,
		UNIT_MOD_FOCUS,
		UNIT_MOD_ENERGY,
		UNIT_MOD_HAPPINESS,
		UNIT_MOD_RUNE,
		UNIT_MOD_RUNIC_POWER,
		UNIT_MOD_ARMOR,                                         // UNIT_MOD_ARMOR..UNIT_MOD_RESISTANCE_ARCANE must be in existed order, it's accessed by index values of SpellSchools enum.
		UNIT_MOD_RESISTANCE_HOLY,
		UNIT_MOD_RESISTANCE_FIRE,
		UNIT_MOD_RESISTANCE_NATURE,
		UNIT_MOD_RESISTANCE_FROST,
		UNIT_MOD_RESISTANCE_SHADOW,
		UNIT_MOD_RESISTANCE_ARCANE,
		UNIT_MOD_ATTACK_POWER,
		UNIT_MOD_ATTACK_POWER_RANGED,
		UNIT_MOD_DAMAGE_MAINHAND,
		UNIT_MOD_DAMAGE_OFFHAND,
		UNIT_MOD_DAMAGE_RANGED,
		UNIT_MOD_END,
		// synonyms
		UNIT_MOD_STAT_START = UNIT_MOD_STAT_STRENGTH,
		UNIT_MOD_STAT_END = UNIT_MOD_STAT_SPIRIT + 1,
		UNIT_MOD_RESISTANCE_START = UNIT_MOD_ARMOR,
		UNIT_MOD_RESISTANCE_END = UNIT_MOD_RESISTANCE_ARCANE + 1,
		UNIT_MOD_POWER_START = UNIT_MOD_MANA,
		UNIT_MOD_POWER_END = UNIT_MOD_RUNIC_POWER + 1,
	}
}
export {};
